export interface CourtCategory {
  label: string;
  courts: string[];
}

export const COURT_CATEGORIES: CourtCategory[] = [
  {
    label: "Supreme Court",
    courts: ["Supreme Court of Nepal"],
  },
  {
    label: "High Courts",
    courts: [
      "High Court Biratnagar",
      "High Court Janakpur",
      "High Court Patan",
      "High Court Pokhara",
      "High Court Tulasipur",
      "High Court Birendranagar",
      "High Court Dipayal",
      "High Court Biratnagar, Dhankuta Bench",
      "High Court Biratnagar, Ilam Bench",
      "High Court Janakpur, Rajbiraj Bench",
      "High Court Patan, Hetauda Bench",
      "High Court Pokhara, Baglung Bench",
      "High Court Tulasipur, Butwal Bench",
      "High Court Tulasipur, Nepalgunj Bench",
      "High Court Birendranagar, Jumla Bench",
      "High Court Dipayal, Mahendranagar Bench",
    ],
  },
  {
    label: "District Courts",
    courts: [
      "Achham District Court",
      "Arghakhanchi District Court",
      "Baglung District Court",
      "Baitadi District Court",
      "Bajhang District Court",
      "Bajura District Court",
      "Banke District Court",
      "Bara District Court",
      "Bardiya District Court",
      "Bhaktapur District Court",
      "Bhojpur District Court",
      "Chitwan District Court",
      "Dadeldhura District Court",
      "Dailekh District Court",
      "Dang District Court",
      "Darchula District Court",
      "Dhading District Court",
      "Dhankuta District Court",
      "Dhanusha District Court",
      "Dolakha District Court",
      "Dolpa District Court",
      "Doti District Court",
      "Eastern Rukum District Court",
      "Gorkha District Court",
      "Gulmi District Court",
      "Humla District Court",
      "Ilam District Court",
      "Jajarkot District Court",
      "Jhapa District Court",
      "Jumla District Court",
      "Kailali District Court",
      "Kalikot District Court",
      "Kanchanpur District Court",
      "Kapilvastu District Court",
      "Kaski District Court",
      "Kathmandu District Court",
      "Kavrepalanchok District Court",
      "Khotang District Court",
      "Lalitpur District Court",
      "Lamjung District Court",
      "Mahottari District Court",
      "Makwanpur District Court",
      "Manang District Court",
      "Morang District Court",
      "Mugu District Court",
      "Mustang District Court",
      "Myagdi District Court",
      "Nawalpur District Court",
      "Nuwakot District Court",
      "Okhaldhunga District Court",
      "Palpa District Court",
      "Panchthar District Court",
      "Parasi District Court",
      "Parbat District Court",
      "Parsa District Court",
      "Pyuthan District Court",
      "Ramechhap District Court",
      "Rasuwa District Court",
      "Rautahat District Court",
      "Rolpa District Court",
      "Rupandehi District Court",
      "Salyan District Court",
      "Sankhuwasabha District Court",
      "Saptari District Court",
      "Sarlahi District Court",
      "Sindhuli District Court",
      "Sindhupalchok District Court",
      "Siraha District Court",
      "Solukhumbu District Court",
      "Sunsari District Court",
      "Surkhet District Court",
      "Syangja District Court",
      "Tanahun District Court",
      "Taplejung District Court",
      "Terhathum District Court",
      "Udayapur District Court",
      "Western Rukum District Court",
    ],
  },
  {
    label: "Specialized Courts & Tribunals",
    courts: [
      "Special Court, Nepal",
      "Administrative Court",
      "Labor Court",
      "Revenue Tribunal, Kathmandu",
      "Revenue Tribunal, Biratnagar",
      "Revenue Tribunal, Pokhara",
      "Revenue Tribunal, Nepalgunj",
      "Foreign Employment Tribunal",
    ],
  },
];

// Re-export as flat list for ease of use if needed elsewhere
export const NEPAL_COURTS = COURT_CATEGORIES.flatMap((c) => c.courts);
